### ISSUE TITLE
Conflict with font-awesome

### ISSUE THREAD

**Issue by herberthamaral** [kkvesper/vesper-icons#4]
Hello,

There seems to have a conflict with font-awesome with at least one icon: the cow one. When I try to add the cow icon, the 'forward' icon appears. Taking a look into vesper-icons' svg and fa's svg, I can see they both use the same code (f04e).

Is there anything we can do about this?

**Comment by johnnyshields** [comment]
@herberthamaral you need to specify `<i class="vs vs-cow"/>` WITHOUT `fa` to avoid conflicts.

Fonts are allowed to use overlapping character codes. (Both Helvetica and Times New Roman contain the letter "A" at the same character code, for example.) You need to specify the right font for the character code.
