### ISSUE TITLE
Use of these icons

### ISSUE THREAD

**Issue by ChiefNetNut** [kkvesper/vesper-icons#6]
Hi I came across these as they have some icons i need to use,

How do i import these into a WordPress website?

Thanks

**Comment by dmhendricks** [comment]
If you're looking to use them with something like WBBakery Page Builder/Visual Composer, you're going to need a theme/plugin that supports importing them and adding them to VS (I can look for one if you like).

If you just want to use them on a WordPress site in the standard WP editor (either via shortcode or standard HTML), I can help you out with that.

**Comment by ChiefNetNut** [comment]
I have created a contact form using contact form 7 and have have used font awesome icons for radio buttons that change colour on selected. I wanted the smoking and no smoking icons from here to do the same thing. The site is currently on MAMP.  Does that help

**Comment by johnnyshields** [comment]
These icons are distributed via NPM. You can download the raw font files from Github. Usage is equivalent to using FontAwesome 4.
